const players = [
    {
        id: 1,
        firstName: "Ksawery",
        lastName: "Jarzębak",
        position: "Pomocnik",
        birthDay: 20,
        birthMonth: 12,
        birthYear: 2012,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR TELEFONU: [ +48 729 979 983 ] NR TELEFONU DO TATY (SEBASTIAN): [ +48 504 016 554 ]"
    },
    {
        id: 2,
        firstName: "Piotr",
        lastName: "Gajowski",
        position: "Napastnik",
        birthDay: 3,
        birthMonth: 7,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 507 215 093] NR DO MAMY: [+48 693 329 626]"
    },
    {
        id: 3,
        firstName: "Mateusz",
        lastName: "Bajger",
        position: "Pomocnik",
        birthDay: 29,
        birthMonth: 10,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 452 403 840] NR DO TATY (KRZYSZTOF): [+48 452 403 840]"
    },
    {
        id: 4,
        firstName: "Filip",
        lastName: "Horzela",
        position: "Napastnik",
        birthDay: 27,
        birthMonth: 2,
        birthYear: 2013,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR [+48 737 307 525]"
    },
    {
        id: 5,
        firstName: "Rostyslav",
        lastName: "Klymenko",
        position: "Pomocnik",
        birthDay: 24,
        birthMonth: 11,
        birthYear: 2012,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 691 777 951] NR DO MAMY: [+48 792 624 516]"
    },
    {
        id: 6,
        firstName: "Mikołaj",
        lastName: "Ludyga",
        position: "Napastnik",
        birthDay: 27,
        birthMonth: 1,
        birthYear: 2014,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 577 747 385] NR DO MAMY (AGNIESZKA): [+48 730 562 221]"
    },
    {
        id: 7,
        firstName: "Marcin",
        lastName: "Kalus",
        position: "Pomocnik",
        birthDay: 24,
        birthMonth: 5,
        birthYear: 2011,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 503 853 512]"
    },
    {
        id: 8,
        firstName: "Michał",
        lastName: "Musialik",
        position: "Obrońca",
        birthDay: 25,
        birthMonth: 11,
        birthYear: 2011,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 506 942 380] NR DO MAMY (KATARZYNA): [+48 500 172 078]"
    },
    {
        id: 9,
        firstName: "Dawid",
        lastName: "Heczko-Wróblewski",
        position: "Pomocnik",
        birthDay: 7,
        birthMonth: 4,
        birthYear: 2012,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 574 146 442]"
    },
    {
        id: 10,
        firstName: "Patryk",
        lastName: "Twardoch",
        position: "Obrońca",
        birthDay: 21,
        birthMonth: 11,
        birthYear: 2012,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 533 929 893]"
    },
    {
        id: 11,
        firstName: "Miłosz",
        lastName: "Piotrowski",
        position: "Pomocnik",
        birthDay: 8,
        birthMonth: 8,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 881 137 620] NR DO TATY (MICHAŁ): [+48 668 612 116]"
    },
    {
        id: 12,
        firstName: "Franciszek",
        lastName: "Lubosik",
        position: "Obrońca",
        birthDay: 22,
        birthMonth: 7,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 783 435 550] NR DO MAMY (MAŁGORZATA): [+48 727 533 467]"
    },
    {
        id: 13,
        firstName: "Piotr",
        lastName: "Szastok",
        position: "Obrońca",
        birthDay: 6,
        birthMonth: 4,
        birthYear: 2010,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 506 046 158]"
    },
    {
        id: 14,
        firstName: "Kacper",
        lastName: "Gajowski",
        position: "Napastnik",
        birthDay: 22,
        birthMonth: 8,
        birthYear: 2013,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 512 578 864]"
    },


    {
        id: 15,
        firstName: "Filip",
        lastName: "Solorz",
        position: "Obrońca",
        birthDay: 22,
        birthMonth: 7,
        birthYear: 2013,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 721 781 419]"
    },
    {
        id: 16,
        firstName: "Filip",
        lastName: "Hojka",
        position: "Obrońca",
        birthDay: 22,
        birthMonth: 7,
        birthYear: 2013,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 511 589 504}"
    },
    {
        id: 17,
        firstName: "Jakub",
        lastName: "Augustyniak",
        position: "Obrońca",
        birthDay: 13,
        birthMonth: 11,
        birthYear: 2013,
        preferredFoot: "Lewa",
        photo: null,
        notes: "NR: [+48 723 863 908]"
    },
     {
        id: 18,
        firstName: "Mateusz",
        lastName: "Czyszoń",
        position: "Bramkarz",
        birthDay: 25,
        birthMonth: 6,
        birthYear: 2010,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 510 621 037] NR DO MAMY (WERONIKA): [+48 506 471 934]"
    },
    {
        id: 19,
        firstName: "Miłosz",
        lastName: "Miller",
        position: "Bramkarz",
        birthDay: 7,
        birthMonth: 9,
        birthYear: 2012,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 501 116 773] NR DO MAMY (WIOLETTA): [+48 503 523 128]"
    },
    {
        id: 20,
        firstName: "Nikodem",
        lastName: "Młokosiewicz",
        position: "Napastnik",
        birthDay: 24,
        birthMonth: 1,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 575 671 599] NR DO MAMY (IZABELA): [+48 503 161 147]"
    },
    {
        id: 21,
        firstName: "Maciek",
        lastName: "Nehrebecki",
        position: "Obrońca",
        birthDay: 9,
        birthMonth: 4,
        birthYear: 2013,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 571 869 235] NR DO MAMY (KATARZYNA): [+48 501 500 842]"
    },
    {
        id: 22,
        firstName: "Bartek",
        lastName: "Juchnik",
        position: "Pomocnik",
        birthDay: 19,
        birthMonth: 6,
        birthYear: 2012,
        preferredFoot: "Prawa",
        photo: null,
        notes: "NR: [+48 571 869 235] NR DO MAMY (ANNA): [+48 782 164 172]"
    },
];